services:
  whisper-asr-webservice:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: askara_whisper_asr_1
    environment:
      - ASR_MODEL=large-v3
      - ASR_ENGINE=whisperx
      - ASR_DEVICE=cuda
      # Best Practice: Configure idle timeouts to save GPU memory
      # Unloads the model from memory after 1800 seconds (30 minutes) of inactivity
      # Disable for now - https://github.com/ahmetoner/whisper-asr-webservice/issues/321
      - MODEL_IDLE_TIMEOUT=0
      # HuggingFace token
      # @see https://ahmetoner.com/whisper-asr-webservice/environmental-variables/#hugging-face-token
      - HF_TOKEN=ChangeMe
    volumes:
      # Best Practice: Persist the downloaded model cache
      # This prevents the model from re-downloading on every container restart
      - ./cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  whisper-asr-webservice-2:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: askara_whisper_asr_2
    environment:
      - ASR_MODEL=large-v3
      - ASR_ENGINE=whisperx
      - ASR_DEVICE=cuda
      # Best Practice: Configure idle timeouts to save GPU memory
      # Unloads the model from memory after 1800 seconds (30 minutes) of inactivity
      # Disable for now - https://github.com/ahmetoner/whisper-asr-webservice/issues/321
      - MODEL_IDLE_TIMEOUT=0
      # HuggingFace token
      # @see https://ahmetoner.com/whisper-asr-webservice/environmental-variables/#hugging-face-token
      - HF_TOKEN=ChangeMe
    volumes:
      # Best Practice: Persist the downloaded model cache
      # This prevents the model from re-downloading on every container restart
      - ./cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:latest
    container_name: askara_whisper_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/whisper_proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - whisper-asr-webservice
      - whisper-asr-webservice-2